// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAinyyR3bLbhQcRR_xRzrKdbiQquSXYMGk',
    appId: '1:1905597203:web:cd2c456a1fbe3aea5a98e6',
    messagingSenderId: '1905597203',
    projectId: 'login-app-flutter-38565',
    authDomain: 'login-app-flutter-38565.firebaseapp.com',
    storageBucket: 'login-app-flutter-38565.firebasestorage.app',
    measurementId: 'G-02Q39QCJEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp7e7kasMSxK5R-s3324HnCoE06yoZDq8',
    appId: '1:1905597203:android:28d844c1c52e5cd85a98e6',
    messagingSenderId: '1905597203',
    projectId: 'login-app-flutter-38565',
    storageBucket: 'login-app-flutter-38565.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_AgEiNxMejIcE3ReNgtf30Kq7K3pr_7E',
    appId: '1:1905597203:ios:86c4211dda77c0dd5a98e6',
    messagingSenderId: '1905597203',
    projectId: 'login-app-flutter-38565',
    storageBucket: 'login-app-flutter-38565.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_AgEiNxMejIcE3ReNgtf30Kq7K3pr_7E',
    appId: '1:1905597203:ios:86c4211dda77c0dd5a98e6',
    messagingSenderId: '1905597203',
    projectId: 'login-app-flutter-38565',
    storageBucket: 'login-app-flutter-38565.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLoginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAinyyR3bLbhQcRR_xRzrKdbiQquSXYMGk',
    appId: '1:1905597203:web:b675e6d4bb6170295a98e6',
    messagingSenderId: '1905597203',
    projectId: 'login-app-flutter-38565',
    authDomain: 'login-app-flutter-38565.firebaseapp.com',
    storageBucket: 'login-app-flutter-38565.firebasestorage.app',
    measurementId: 'G-JPNM21VWWV',
  );
}
